const wordList = [
    { foreign: "סַרְקַסְטִי", hebrew: "עוֹקְצָנִי" },
    { foreign: "נָאִיבִי", hebrew: "תָּמִים" },
    { foreign: "נָאִיבִיּוֹת", hebrew: "תְּמִימוּת" },
    { foreign: "נֵגָטִיבִי", hebrew: "שְׁלִילִי" },
    { foreign: "נוֹמִינָלִי", hebrew: "נָקוּב" },
    { foreign: "נוֹן־קוֹנְפוֹרְמִיזְם", hebrew: "אִי תַּלְמָנוּת" },
    { foreign: "נוֹן־קוֹנְפוֹרְמִיסְט", hebrew: "לֹא תַּלְמָן" },
    { foreign: "נוֹנְסֵנְס", hebrew: "אִי־גָּיוֹן" },
    { foreign: "נוּקְלֵאָרִי", hebrew: "גַּרְעִינִי" },
    { foreign: "נוֹרְמָה", hebrew: "תֶּקֶן" },
    { foreign: "נוֹרְמָטִיבִיזְם", hebrew: "פּוֹסְקָנוּת" },
    { foreign: "נוֹרְמָטִיבִיסְט", hebrew: "פּוֹסְקָנִי" },
    { foreign: "נְיוּאַנְס", hebrew: "גּוֹנִית" },
    { foreign: "נְיוּזְלֵטֶר", hebrew: "אִגֶּרֶת מֵידָע" },
    { foreign: "נִיט", hebrew: "מַסְמֶרֶת" },
    { foreign: "נִישָׁה", hebrew: "גֻּמְחָה" },
    { foreign: "נֶפְּטוּן", hebrew: "רַהַב" },
    { foreign: "נַצְיוֹנָלִי", hebrew: "לְאֻמִּי" },
    { foreign: "נַצְיוֹנָלִיזְם", hebrew: "לְאֻמָּנוּת" },
    { foreign: "נַצְיוֹנָלִיסְטִי", hebrew: "לְאֻמָּנִי" },
    { foreign: "נָרָטִיב", hebrew: "סִפֵּר" }
];
