const wordList = [
    { foreign: "סֶפְּטוּאָגִינְטָה", hebrew: "תַּרְגּוּם הַשִּׁבְעִים" },
    { foreign: "סְפִּידוֹמֵטֶר", hebrew: "מַד מְהִירוּת" },
    { foreign: "סְפֶּיְשֶׁל", hebrew: "מְיֻחָד" },
    { foreign: "סְפִּין", hebrew: "סַחְרִיר" },
    { foreign: "סְפִּירָלִי", hebrew: "לוּלְיָנִי" },
    { foreign: "סְפְּרֵי", hebrew: "תַּרְסִיס" },
    { foreign: "ספרינט", hebrew: "מָאוֹץ" },
    { foreign: "סְפְּרִינְטֶר", hebrew: "אָצָן" },
    { foreign: "ספרינקלר", hebrew: "מַתָּז" },
    { foreign: "סְצֵנַרְיוֹ", hebrew: "תַּרְחִישׁ" },
    { foreign: "סקוואט", hebrew: "שְׁפִיפָה" },
    { foreign: "סְקוֹלֵרִיזַצְיָה", hebrew: "חִלּוּן" },
    { foreign: "סְקוֹטְשְׁבְּרַיְט", hebrew: "מְשׁוּפָה" },
    { foreign: "סֶקְטוֹר", hebrew: "מִגְזָר" },
    { foreign: "סֶקְטוֹרְיָאלִי", hebrew: "מִגְזָרִי" },
    { foreign: "סקטים", hebrew: "גַּלְגִּלִּיּוֹת" },
    { foreign: "סְקֶיְטְבּוֹרְד", hebrew: "גַּלְגֶּשֶׁת" },
    { foreign: "סְקִיפֶּר", hebrew: "מֵשִׁיט" },
    { foreign: "סֶרְוִיס", hebrew: "מַעֲרֶכֶת כֵּלִים" },
    { foreign: "סֶרְיָה", hebrew: "סִדְרָה" },
    { foreign: "סֵרֵנָדָה", hebrew: "רַמְשִׁית" },
    { foreign: "סֶרְפֶּנְטִינֶה", hebrew: "נַחְשׁוֹן" },
    { foreign: "סַרְקַזְם", hebrew: "עוֹקְצָנוּת" },
    { foreign: "סַרְקַסְטִי", hebrew: "עוֹקְצָנִי" },
    { foreign: "נָאִיבִי", hebrew: "תָּמִים" },
    { foreign: "נָאִיבִיּוֹת", hebrew: "תְּמִימוּת" },
    { foreign: "נֵגָטִיבִי", hebrew: "שְׁלִילִי" },
    { foreign: "נוֹמִינָלִי", hebrew: "נָקוּב" },
    { foreign: "נוֹן־קוֹנְפוֹרְמִיזְם", hebrew: "אִי תַּלְמָנוּת" },
    { foreign: "נוֹן־קוֹנְפוֹרְמִיסְט", hebrew: "לֹא תַּלְמָן" },
    { foreign: "נוֹנְסֵנְס", hebrew: "אִי גָיוֹן" },
    { foreign: "נוקליארי", hebrew: "גַּרְעִינִי" },
    { foreign: "נוֹרְמָה", hebrew: "תֶּקֶן" },
    { foreign: "נוֹרְמָטִיבִיזְם", hebrew: "פּוֹסְקָנוּת" },
    { foreign: "נוֹרְמָטִיבִיסְט", hebrew: "פּוֹסְקָנִי" },
    { foreign: "נְיוּאַנְס", hebrew: "גּוֹנִית" },
    { foreign: "נְיוּזְלֵטֶר", hebrew: "אִגֶּרֶת מֵידָע" },
    { foreign: "נִיט", hebrew: "מַסְמֶרֶת" },
    { foreign: "נִישָׁה", hebrew: "גֻּמְחָה" },
    { foreign: "נֶפְּטוּן", hebrew: "רַהַב" },
    { foreign: "נַצְיוֹנָלִי", hebrew: "לְאֻמִּי" },
    { foreign: "נַצְיוֹנָלִיזְם", hebrew: "לְאֻמָּנוּת" },
    { foreign: "נַצְיוֹנָלִיסְטִי", hebrew: "לְאֻמָּנִי" },
    { foreign: "נָרָטִיב", hebrew: "סִפֵּר" },
    { foreign: "נַרְקוֹטִי", hebrew: "מַרְדִּים" },
    { foreign: "סוֹלָארִי", hebrew: "שִׁמְשִׁי" },
    { foreign: "סופיקס", hebrew: "סוֹפִית" },
    { foreign: "סוּפְלֶה", hebrew: "תְּפִיחָה" },
    { foreign: "סופלציה", hebrew: "תַּשְׁלִים" },
    { foreign: "סוּפֶּרְמַרְקֶט", hebrew: "מַרְכּוֹל" },
    { foreign: "סוֹצְיָאלִי", hebrew: "חֶבְרָתִי" },
    { foreign: "סוֹצְיָאלִיזְם", hebrew: "חֶבְרָתָנוּת" },
    { foreign: "סוֹצְיוֹאֵקוֹנוֹמִי", hebrew: "חֶבְרָתִי כַּלְכָּלִי" },
    { foreign: "סְטָאר", hebrew: "כּוֹכָב" },
    { foreign: "סְטַארְט־אַפְּ", hebrew: "חֶבְרַת הֶזְנֵק" },
    { foreign: "סְטַבִּילִי", hebrew: "יַצִּיב" },
    { foreign: "סְטַבִּילִיּוֹת", hebrew: "יַצִּיבוּת" },
    { foreign: "סְטַגְנַצְיָה", hebrew: "קִפָּאוֹן" },
    { foreign: "סְטוּדְיוֹ", hebrew: "אֻלְפָּן" },
    { foreign: "סְטוֹפֶּר", hebrew: "שְׁעוֹן עֶצֶר" },
    { foreign: "סְטוֹק", hebrew: "מְלַאי" },
    { foreign: "סָטוּרְן", hebrew: "שַׁבְּתַאי" },
    { foreign: "סטאז'", hebrew: "הִתְמַחוּת" },
    { foreign: "סטאז'ר", hebrew: "מִתְמַחֶה" },
    { foreign: "סְטָטוּטוֹרִי", hebrew: "חָקוּק" },
    { foreign: "סְטָטוּס קְווֹ", hebrew: "הַמַּצָּב הַקַּיָּם" },
    { foreign: "סְטָטִיסְט", hebrew: "נִצָּב" },
    { foreign: "סְטַיְל", hebrew: "סִגְנוֹן" },
    { foreign: "סְטִיקְלַיְט", hebrew: "מַקְלוֹר" },
    { foreign: "סְטִיקֶר", hebrew: "דִּבְקִית" },
    { foreign: "סְטֵנְד־אַפּ קוֹמֵדִי", hebrew: "מִצְחָק" },
    { foreign: "סְטַנְדַּרְט", hebrew: "תֶּקֶן" },
    { foreign: "סְטַנְדַּרְטִי", hebrew: "תִּקְנִי" },
    { foreign: "סטנוגרף", hebrew: "קַצְרָן" },
    { foreign: "סְטָנוֹגְרַפְיָה", hebrew: "קַצְרָנוּת" },
    { foreign: "סטנט", hebrew: "תּוֹמְכָן" },
    { foreign: "סְטֵרֵאוֹטִיפּ", hebrew: "הֶטְפֵּס" },
    { foreign: "סְטֵרֵאוֹטִיפִּי", hebrew: "הֶטְפֵּסִי" },
    { foreign: "סטרוק", hebrew: "שָׁבָץ מֹחִי" },
    { foreign: "סְטְרוּקְטוּרָה", hebrew: "מִבְנֶה" },
    { foreign: "סְטְרוּקְטוּרָלִי", hebrew: "מִבְנִי" },
    { foreign: "סְטַרְטֶר", hebrew: "מַתְנֵעַ" },
    { foreign: "סְטֵרִילִי", hebrew: "מְעֻקָּר" },
    { foreign: "סְטֵרִילִיזַצְיָה", hebrew: "עִקּוּר" },
    { foreign: "סְטְרִימֶר", hebrew: "מַזְרִים" },
    { foreign: "סְטְרִינְג", hebrew: "מַחְרֹזֶת" },
    { foreign: "סְטְרֵס", hebrew: "עָקָה" },
    { foreign: "סטתוסקופ", hebrew: "מַסְכֵּת" },
    { foreign: "סִיגְנָל", hebrew: "אוֹת" },
    { foreign: "סִיטוּאַצְיָה", hebrew: "מַצָּב" },
    { foreign: "סִיטְקוֹם", hebrew: "קוֹמֶדְיַת מַצָּבִים" },
    { foreign: "סַיְבֶּר", hebrew: "סֵבֶר" },
    { foreign: "סִילִיקוֹן", hebrew: "צוֹרָן" },
    { foreign: "סִימְבּוֹל", hebrew: "סֵמֶל" },
    { foreign: "סִימְבּוֹלִי", hebrew: "סִמְלִי" },
    { foreign: "סִימְבְּיוֹזָה", hebrew: "צַוְתָּאוּת" },
    { foreign: "סִימוּלָטוֹר", hebrew: "מַדְמֶה" },
    { foreign: "סָנִיטָר", hebrew: "עַזְרָן" },
    { foreign: "סֶנְסוֹר", hebrew: "חַיְשָׁן" },
    { foreign: "סֶנְסַצְיָה", hebrew: "מִרְעָשׁ" },
    { foreign: "סֶנְסַצְיוֹנִי", hebrew: "מַרְעִישׁ" },
    { foreign: "סְנֶפְּלִינְג", hebrew: "גְּלִישַׁת חֶבֶל" },
    { foreign: "סַנְקְצִיּוֹת", hebrew: "עִצּוּמִים" },
    { foreign: "סְפּוֹיְלֶר", hebrew: "קַלְקְלָן" },
    { foreign: "סְפּוֹנְטָנִי", hebrew: "עַצְמוֹנִי" },
    { foreign: "סְפּוֹנְסֶר", hebrew: "נוֹתֵן חָסוּת" },
    { foreign: "סְפּוֹרָדִי", hebrew: "נִקְרֶה" },
    { foreign: "גְּרִיפָּה", hebrew: "שַׁפַּעַת" },
    { foreign: "גְּרַנְט", hebrew: "מַעֲנָק" },
    { foreign: "גְּרָנִיט", hebrew: "שַׁחַם" },
    { foreign: "גרפס", hebrew: "גִּהוּק" },
    { foreign: "יוּ טרן", hebrew: "פְּנִיַּת פַּרְסָה" },
    { foreign: "יודל", hebrew: "יִדְלוּל" },
    { foreign: "יוּפִּיטֶר", hebrew: "צֶדֶק" },
    { foreign: "כָּאוֹס", hebrew: "תֹּהוּ וָבֹהוּ" },
    { foreign: "כוסברה", hebrew: "גָּד" },
    { foreign: "כּוֹרֵאוֹגְרָף", hebrew: "יוֹצֵר מְחוֹלוֹת" },
    { foreign: "כּוֹרֵאוֹגְרַפְיָה", hebrew: "יְצִירַת מְחוֹלוֹת" },
    { foreign: "כִּירוּרְגִּי", hebrew: "נִתּוּחִי" },
    { foreign: "כְּרוֹמָטִי", hebrew: "צִבְעִי" },
    { foreign: "בִּיפֶּר", hebrew: "זִימוֹנִית" },
    { foreign: "בְּלוֹג", hebrew: "יוֹמַן רֶשֶׁת" },
    { foreign: "בְּלוֹקָדָה", hebrew: "הֶסְגֵּר" },
    { foreign: "בִּיג דָּאטָה", hebrew: "נְתוּנֵי עָתֵק" },
    { foreign: "בִּיּוֹגְרַפְיָה", hebrew: "סִפּוּר חַיִּים" },
    { foreign: "בְּלִינְצֶ'ס", hebrew: "חֲבִיתִיּוֹת" },
    { foreign: "בְּלִיץ", hebrew: "מִלְחֶמֶת בָּזָק" },
    { foreign: "בְּלֶנְדֶּר", hebrew: "מַמְחֶה" },
    { foreign: "בָּלַנְס", hebrew: "אִזּוּן" },
    { foreign: "בלקאאוט", hebrew: "חִשָּׁכוֹן" },
    { foreign: "בַּלְקוֹן", hebrew: "גְּזֻזְטְרָה" },
    { foreign: "בַּמְבּוּק", hebrew: "חִזְרָן" },
    { foreign: "בֵּמוֹל", hebrew: "נָחֵת" },
    { foreign: "בְּמֵפֵר", hebrew: "פַּס הֶאָטָה" },
    { foreign: "בָּנָלִי", hebrew: "נָדוֹשׁ" },
    { foreign: "בֶּסְט סֶלֶר", hebrew: "רַב מֶכֶר" },
    { foreign: "בַּקְטֶרְיָה", hebrew: "חַיְדַּק" },
    { foreign: "בְּקַלָּה", hebrew: "זְאֵב יָם" },
    { foreign: "בַּר מַיִם", hebrew: "מַרְוָן" },
    { foreign: "בְּרָאוּזֶר", hebrew: "דַּפְדְּפָן" },
    { foreign: "בְּרֵאוּנִיס", hebrew: "חוּמִיּוֹת" },
    { foreign: "בְּרוֹנְזָה", hebrew: "אָרָד" },
    { foreign: "בְּרוֹקֵר", hebrew: "עֲמִיל בּוּרְסָה" },
    { foreign: "בֵּרֵט", hebrew: "כֻּמְתָּה" },
    { foreign: "בַּרְטֶר", hebrew: "סַחַר חֲלִיפִין" },
    { foreign: "בְּרִיגָדָה", hebrew: "חֲטִיבָה" },
    { foreign: "בְּרִיזָה", hebrew: "רוּחַ יָם" },
    { foreign: "בְּרִיף", hebrew: "תַּדְרִיךְ" },
    { foreign: "בָּרִיקָדָה", hebrew: "מִתְרָס" },
    { foreign: "בֶּרְמָן", hebrew: "מוֹזֵג" },
    { foreign: "בְּרֶנְדִּי", hebrew: "יֵין שָׂרָף" },
    { foreign: "בְּרֵנֶר", hebrew: "מַבְעֵר" },
    { foreign: "בַּרְקוֹד", hebrew: "קוֹד קַוִּים" },
    { foreign: "בְּרֶקְס", hebrew: "בְּלָמִים" },
    { foreign: "סָאוּנְד", hebrew: "צְלִיל" },
    { foreign: "סָאוּנְד טָרַק", hebrew: "פַּסְקוֹל" },
    { foreign: "סַבְּלֵט", hebrew: "שְׂכִירוּת מִשְׁנֶה" },
    { foreign: "סָגָוִיי", hebrew: "רְכִינוֹעַ" },
    { foreign: "סֶגְמֶנְט", hebrew: "מִקְטָע" },
    { foreign: "סוּבְּיֵקְט", hebrew: "נוֹשֵׂא" },
    { foreign: "סוּבֵרֵנִי", hebrew: "רִבּוֹנִי" },
    { foreign: "סוגסטייה", hebrew: "הַשָּׁאָה" },
    { foreign: "סוֹדִיּוּם", hebrew: "נַתְרָן" },
    { foreign: "סְוֵדֶר", hebrew: "סֻרְגָּה" },
    { foreign: "סְוִיץ'", hebrew: "מֶתֶג" },
    { foreign: "סוֹל (דָּג)", hebrew: "סַנְדָּל" },
    { foreign: "סוֹלִידָרִיּוּת", hebrew: "אַחְוָה" },
    { foreign: "סוֹלִיסְט", hebrew: "סוֹלָן" },
    { foreign: "סולפט", hebrew: "גָּפְרָה" },
    { foreign: "תֵּרָפּוֹיְטִי", hebrew: "רִפּוּיִי" },
    { foreign: "ז'וּרְנָל", hebrew: "כְּתַב עֵת" },
    { foreign: "זֵ'טוֹן", hebrew: "אֲסִימוֹן" },
    { foreign: "זָ'אנֶר", hebrew: "סוּגָה" },
    { foreign: "זָ'קֵט", hebrew: "מִקְטֹרֶן" },
    { foreign: "זוּם אָאוּט", hebrew: "הַרְחָבָה" },
    { foreign: "זוּם אִין", hebrew: "הַצָּרָה" },
    { foreign: "זוֹנְדָּה", hebrew: "מַחְדֵּר" },
    { foreign: "זִיגְזָג", hebrew: "סִכְסָךְ" },
    { foreign: "זַעְתָּר", hebrew: "אֵזוֹב" },
    { foreign: "זפזופ", hebrew: "שִׁלְטוּט" },
    { foreign: "הָאקֶר", hebrew: "פַּצְחָן" },
    { foreign: "הַארְד קוֹפִּי", hebrew: "עֹתֶק מֻדְפָּס" },
    { foreign: "הַשְׁטָג", hebrew: "תַּג הַקְבָּצָה" },
    { foreign: "הַגְיוֹגְרַפְיָה", hebrew: "קוֹרוֹת קְדוֹשִׁים" },
    { foreign: "הֵדוֹנִיזְם", hebrew: "נֶהֶנְתָנוּת" },
    { foreign: "הֵדוֹנִיסְט", hebrew: "נֶהֶנְתָן" },
    { foreign: "הוֹבִּי", hebrew: "תַּחְבִּיב" },
    { foreign: "הוֹט סְפּוֹט", hebrew: "מוֹקְדָה" },
    { foreign: "הוֹלִיזְם", hebrew: "כֻּלִּיּוּת" },
    { foreign: "הוֹמוֹגֵנִי", hebrew: "אָחִיד" },
    { foreign: "הוֹמוֹגֵנִיּוּת", hebrew: "אֲחִידוּת" },
    { foreign: "הוֹמְלֶס", hebrew: "דַּר רְחוֹב" },
    { foreign: "הוּמָנִי", hebrew: "אֱנוֹשִׁי" },
    { foreign: "הוּמָנִיּוּת", hebrew: "אֱנוֹשִׁיּוּת" },
    { foreign: "הוֹסְטֵל", hebrew: "מְעוֹנִית" },
    { foreign: "הוֹרִיזוֹנְטָלִי", hebrew: "אָפְקִי" },
    { foreign: "הֶטְרוֹגֵנִי", hebrew: "לֹא אָחִיד" },
    { foreign: "הִיגְיֵנָה", hebrew: "גֵּהוּת" },
    { foreign: "הִידְרוֹפוֹבְּיָה", hebrew: "בַּעַת מַיִם" },
    { foreign: "הִידֵּרוֹפִיט", hebrew: "צֶמַח מַיִם" },
    { foreign: "הַי־טֵק", hebrew: "טֶכְנוֹלוֹגְיָה עִלִּית" },
    { foreign: "הִיֵּרוֹגְלִיפִים", hebrew: "כְּתַב חַרְטֻמִּים" },
    { foreign: "הִיֵּרַרְכִיָּה", hebrew: "מִדְרָג" },
    { foreign: "הִיפּוֹפּוֹטָם", hebrew: "סוּס יְאוֹר" },
    { foreign: "הִיפּוֹתֵזָה", hebrew: "הַשְׁעָרָה" },
    { foreign: "הִיפּוֹתֶרְמְיָה", hebrew: "תַּת חֹם" },
    { foreign: "הָלוּצִינַצְיָה", hebrew: "חֶזְיוֹן שָׁוְא" },
    { foreign: "הֵלִיקוֹפְּטֶר", hebrew: "מַסּוֹק" },
    { foreign: "הֶנְגְּאוֹבֵר", hebrew: "חֲמַרְמֹרֶת" },
    { foreign: "הנדברקס", hebrew: "בֶּלֶם יָד" },
    { foreign: "הֶנְדִּימֶן", hebrew: "תִּקּוּנַאי" },
    { foreign: "הֶפְּטָגוֹן", hebrew: "מְשֻׁבָּע" },
    { foreign: "הֶקְסָגוֹן", hebrew: "מְשֻׁשֶּׁה" },
    { foreign: "הֵרִינְג", hebrew: "מָלִיחַ" },
    { foreign: "הַרְמוֹנְיָה", hebrew: "תֹּאַם" },
    { foreign: "הַרְמוֹנִיקָה", hebrew: "מַפּוּחִית" },
    { foreign: "הֶרְמֵטִי", hebrew: "אָטוּם" },
    { foreign: "הֶרְנִיָּה", hebrew: "בֶּקַע" },
    { foreign: "עֲלֵי בייבי", hebrew: "עַלְעַלִּים" },
    { foreign: "ח'אפר", hebrew: "חַטְפָנִית" },
    { foreign: "ח'וביזה", hebrew: "חֶלְמִית" },
    { foreign: "חוֹלִיגָנִיזְם", hebrew: "בִּרְיוֹנוּת" },
    { foreign: "חוּמוּס", hebrew: "חִמְצָה" },
    { foreign: "חֲזָרָה גֵּנֵרָלִית", hebrew: "חֲזָרָה כְּלָלִית" },
    { foreign: "חַמְסִין", hebrew: "שָׁרָב" },
    { foreign: "גַּ'אגְלִינְג", hebrew: "לִהֲטוּט" },
    { foreign: "גַ'נְק", hebrew: "זִבּוּרִי" },
    { foreign: "גַ'נְק פּוּד", hebrew: "זְלֹלֶת" },
    { foreign: "ג'וּנְגֵּל", hebrew: "יַעַר עַד" },
    { foreign: "גֵּ'ט לג", hebrew: "יַעֶפֶת" },
    { foreign: "גִ'י־פִּי־אֵס", hebrew: "נַוְטָן" },
    { foreign: "גִ'יבְּרִישׁ", hebrew: "קַשְׁקֶשֶׁת" },
    { foreign: "גִ'יג", hebrew: "מקבע" },
    { foreign: "גִּ'ינְגֶ'ר", hebrew: "זַנְגְּבִיל" },
    { foreign: "גִ'ינְגֵּל", hebrew: "זַמְרִיר" },
    { foreign: "גֵּ'ל", hebrew: "תַּקְרִישׁ" },
    { foreign: "גֵ'לִי", hebrew: "מִקְפָּא" },
    { foreign: "גָ'מוּס", hebrew: "תֵּאוֹ" },
    { foreign: "ג'נדר", hebrew: "מִגְדָּר" },
    { foreign: "גֵּ'נוֹסַיְד", hebrew: "הַשְׁמָדַת עַם" },
    { foreign: "גֶ'סְטָה", hebrew: "מֶחֱוָה" },
    { foreign: "גֵ'ק", hebrew: "מַגְבֵּהַּ" },
    { foreign: "גָ'קוּזִי", hebrew: "אַמְבַּט עִסּוּי" },
    { foreign: "גאג'ט", hebrew: "חֲפִיץ" },
    { foreign: "גּוֹל", hebrew: "שַׁעַר" },
    { foreign: "גזיבו", hebrew: "סוֹכְכָה" },
    { foreign: "גֶּיְמִינְג", hebrew: "מִשְׂחֲקָנוּת" },
    { foreign: "גֶּיְמֶר", hebrew: "מִשְׂחֲקָן" },
    { foreign: "גִּינֵקוֹלוֹג", hebrew: "רוֹפֵא נָשִׁים" },
    { foreign: "גִּינֵקוֹלוֹגְיָה", hebrew: "רְפוּאַת נָשִׁים" },
    { foreign: "גַּלְדִּיָּאטוֹר", hebrew: "לוּדָר" },
    { foreign: "גְּלַדְיוֹלָה", hebrew: "סַיְּפָן" },
    { foreign: "גְּלוֹבָּלִי", hebrew: "עוֹלָמִי" },
    { foreign: "גְּלוּטֵן", hebrew: "דִּבְקָן" },
    { foreign: "גְּלָזוּרָה", hebrew: "זִגּוּג" },
    { foreign: "גֵּנֵרָטוֹר", hebrew: "מְחוֹלֵל" },
    { foreign: "גֵּנֵרִי", hebrew: "סוּגָנִי" },
    { foreign: "גראז'", hebrew: "מֵוֵסְךְ" },
    { foreign: "גרדרובה", hebrew: "מֶלְתָּחָה" },
    { foreign: "גְּרָוִיטַצְיָה", hebrew: "כְּבִידָה" },
    { foreign: "גְּרִיז", hebrew: "דֹּהַן" },
    { foreign: "גְּרִיפ", hebrew: "תַּמְכָן" },
    { foreign: "דֵּפִיצִיט", hebrew: "גֵּרָעוֹן" },
    { foreign: "דפנסיבה", hebrew: "מִגְנָנָה" },
    { foreign: "דֵּפֶנְסִיבִי", hebrew: "מִתְגּוֹנֵן" },
    { foreign: "דק", hebrew: "סֶפֶן" },
    { foreign: "דֵּקוֹנְסְטְרוּקְצְיָה", hebrew: "פֵּרוּק" },
    { foreign: "דֵּקוֹרָטִיבִי", hebrew: "קִשּׁוּטִי" },
    { foreign: "דֶּקְלָרָטִיבִי", hebrew: "הַצְהָרָתִי" },
    { foreign: "דֵּקֵלֶרְצִיָּה", hebrew: "הַצְהָרָה" },
    { foreign: "צַ'אנְס", hebrew: "סִכּוּי" },
    { foreign: "צ'וֹק", hebrew: "מַשְׁנֵק" },
    { foreign: "צֵ'ט", hebrew: "שִׂיחוּחַ" },
    { foreign: "צִ'יטָה", hebrew: "בַּרְדְּלָס" },
    { foreign: "צ'יינג'", hebrew: "חַלְפָנִיָּה" },
    { foreign: "צִ'ימִידָן", hebrew: "צִיּוּדָן" },
    { foreign: "צִ'יפּ", hebrew: "שְׁבָב" },
    { foreign: "צֵ'ק", hebrew: "הַמְחָאָה" },
    { foreign: "צ'קלקה", hebrew: "צְפִירוֹר" },
    { foreign: "צִינְק", hebrew: "אָבָץ" },
    { foreign: "צֶלוֹלִיטִיס", hebrew: "רַקֶּמֶת" },
    { foreign: "צליאק", hebrew: "דַּגֶּנֶת" },
    { foreign: "צֶנְזוֹר", hebrew: "גִּנְזָר" },
    { foreign: "צֶנְזוּרָה", hebrew: "גִּנְזָרוּת" },
    { foreign: "צֶנְטְרִיפוּגָה", hebrew: "סַרְכֶּזֶת" },
    { foreign: "צֶנְטְרָלִיזַצְיָה", hebrew: "מִרְכּוּז" },
    { foreign: "בִּינְג'", hebrew: "צְפִיַּת רֶצֶף" },
    { foreign: "צרמוניה", hebrew: "טֶקֶס" },
    { foreign: "קָאוּבּוֹי", hebrew: "בּוֹקֵר" },
    { foreign: "קַבִּינָה", hebrew: "תָּא" },
    { foreign: "קוֹאוֹפֵּרָטִיב", hebrew: "אֲגֻדָּה שִׁתּוּפִית" },
    { foreign: "קוֹאוֹפֵּרַצְיָה", hebrew: "שִׁתּוּף פְּעֻלָּה" },
    { foreign: "קוֹאוֹצִ'ינְג", hebrew: "אִמּוּן" },
    { foreign: "קוֹאוֹרְדִּינַצְיָה", hebrew: "תֵּאוּם" },
    { foreign: "קוֹאָלִיצְיָה", hebrew: "יַחְדָּה" },
    { foreign: "קוגלגר", hebrew: "מֵסַב כַּדּוּרִי" },
    { foreign: "קוֹגְנִיטִיבִי", hebrew: "הַכָּרָנִי" },
    { foreign: "קוֹדֵקְס", hebrew: "מִצְחָף" },
    { foreign: "קוֹהֵרֶנְטִי", hebrew: "לָכִיד" },
    { foreign: "קוֹהֵרֶנְטִיּוּת", hebrew: "לְכִידוּת" },
    { foreign: "קְוִינְטֵט", hebrew: "חֲמִישִׁיָּה" },
    { foreign: "קְוַרְטֵט", hebrew: "רְבִיעִיָּה" },
    { foreign: "קולג'", hebrew: "מִכְלָלָה" },
    { foreign: "קוֹלֵגָה", hebrew: "עָמִית" },
    { foreign: "קוֹלֶגְיָאלִיּוֹת", hebrew: "עֲמִיתָנוּת" },
    { foreign: "קוֹלוֹנְיָה", hebrew: "מוֹשָׁבָה" },
    { foreign: "קוֹלָז'", hebrew: "הֶדְבֵּק" },
    { foreign: "קוּלְטוּרָה", hebrew: "תַּרְבּוּת" },
    { foreign: "קוליס", hebrew: "עַקְבּוּב" },
    { foreign: "קוֹמוּנִיקָטִיבִי", hebrew: "תִּקְשָׁרְתִּי" },
    { foreign: "קוֹמוּנִיקַצְיָה", hebrew: "תִּקְשֹׁרֶת" },
    { foreign: "קוֹמִיקְס", hebrew: "עֲלִילוֹן" },
    { foreign: "קוֹמְפּוֹזִיטוֹר", hebrew: "מַלְחִין" },
    { foreign: "קוֹמְפּוֹט", hebrew: "לִפְתָּן" },
    { foreign: "קוֹמְפּוּלְסִיבִי", hebrew: "כְּפִיָּתִי" },
    { foreign: "קוֹמְפּוֹנֵנְט", hebrew: "רְכִיב" },
    { foreign: "קוֹמְפּוֹסְט", hebrew: "דְּשֹׁנֶת" },
    { foreign: "קוֹמְפּוֹסְטֶר", hebrew: "מִדֶּשֶׁן" },
    { foreign: "קוֹמְפְּיוּטֶר", hebrew: "מַחְשֵׁב" },
    { foreign: "קוֹמְפְּלִימֵנְט", hebrew: "מַחֲמָאָה" },
    { foreign: "קוֹמְפַּקְטִי", hebrew: "צָמוּם" },
    { foreign: "קוֹמְפְּרֵס", hebrew: "רְטִיָּה" },
    { foreign: "קוֹמְפְּרֵסוֹר", hebrew: "מַדְחֵס" },
    { foreign: "קוֹנְדּוֹקְטוֹר", hebrew: "כַּרְטִיסָן" },
    { foreign: "קוֹנְדִּיטָאוּת", hebrew: "מִגְדְּנָאוּת" },
    { foreign: "קוֹנְדִּיטוֹר", hebrew: "מִגְדְּנַאי" },
    { foreign: "קוֹנְדִּיטוֹרְיָה", hebrew: "מִגְדָּנִיָּה" },
    { foreign: "קוֹנְדִּישְׁנֶר", hebrew: "מְרַכֵּךְ שֵׂעָר" },
    { foreign: "קוֹנְוֶנְצִיָּה", hebrew: "מֻסְכָּמָה" },
    { foreign: "קוֹנוּס", hebrew: "חָרוּט" },
    { foreign: "קוֹנְטֶיְנֶר", hebrew: "מְכוּלָה" },
    { foreign: "קוֹנְטִינֵנְט", hebrew: "יַבֶּשֶׁת" },
    { foreign: "קוֹנְטַקְט", hebrew: "מַגָּע" },
    { foreign: "קוֹנְטֵקְסְט", hebrew: "הֶקְשֵׁר" },
    { foreign: "קוֹנְטְרַבָּס", hebrew: "בַּטְנוּן" },
    { foreign: "קונטרוברסיאלי", hebrew: "מְעוֹרֵר מַחְלֹקֶת" },
    { foreign: "קוֹנְטְרַסְט", hebrew: "נִגּוּד" },
    { foreign: "קוֹנְטְרַסְטִי", hebrew: "מְנֻגָּד" },
    { foreign: "קוֹנְסוֹנְנֵט", hebrew: "עִצּוּר" },
    { foreign: "קוֹנְסוֹרְצְיוּם", hebrew: "מְאַגֵּד" },
    { foreign: "קוֹנְסְטִיטוּצְיָה", hebrew: "חֻקָּה" },
    { foreign: "קוֹנְסְטִיטוּצְיוֹנִי", hebrew: "חֻקָּתִי" },
    { foreign: "קוֹנְסְטְרוֹקְטוּר", hebrew: "מְהַנְדֵּס מִבְנִים" },
    { foreign: "קוֹנְסְטְרוּקְצִיָּה", hebrew: "מִבְנֶה" },
    { foreign: "קוֹנְסִיסְטֶנְטִי", hebrew: "עָקִיב" },
    { foreign: "קוֹנְסִיסְטֶנְטִיּוּת", hebrew: "עֲקִיבוּת" },
    { foreign: "קוֹנְסֵפְּט", hebrew: "מֻשָּׂג" },
    { foreign: "קוֹנְסֶפְּטוּאָלִי", hebrew: "מֻשָּׂגִי" },
    { foreign: "קוֹנְסֶפְּטוּאָלִיזַצְיָה", hebrew: "הַמְשָׂגָה" },
    { foreign: "קונספירטור", hebrew: "קוֹשֵׁר" },
    { foreign: "קוֹנְסְפִּירַצְיָה", hebrew: "קֶשֶׁר" },
    { foreign: "קוֹנְסֶפְּצִיָּה", hebrew: "תְּפִיסָה" },
    { foreign: "קוֹנְסֶרְבָטִיזְם", hebrew: "שַׁמְרָנוּת" },
    { foreign: "קונסרבים", hebrew: "שִׁמּוּרִים" },
    { foreign: "קוֹנְפֵדֵרַצְיָה", hebrew: "תַּאֲחִיד" },
    { foreign: "קוֹנְפוֹרְמִיּוּת", hebrew: "תַּלְמִיּוֹת" },
    { foreign: "קוֹנְפֵטִי", hebrew: "פְּתִיתוֹנִים" },
    { foreign: "קוֹנְצֵרְן", hebrew: "תִּשְׁלֹבֶת" },
    { foreign: "קונקשן", hebrew: "טִיסַת הֶמְשֵׁךְ" },
    { foreign: "קַלְצְיוּם", hebrew: "סִידָן" },
    { foreign: "קְלָרִינֵט", hebrew: "קְלַרְנִית" },
    { foreign: "קַמְפּוּס", hebrew: "קִרְיָה" },
    { foreign: "קַמְפֵּיְן", hebrew: "מַסַּע פִּרְסוּם" },
    { foreign: "קֶמְפִּינְג", hebrew: "מַחֲנָקָה" },
    { foreign: "קַנְדִּידָט", hebrew: "מֻעֲמָד" },
    { foreign: "קניידל", hebrew: "כֻּפְתָּה" },
    { foreign: "קָרוּסֵלָה", hebrew: "סְחַרְחָרָה" },
    { foreign: "קְרוֹקוֹדִיל", hebrew: "תַּנִּין" },
    { foreign: "קַרְטוֹגְרָף", hebrew: "מַפַּאי" },
    { foreign: "קַרְטוֹגְרַפְיָה", hebrew: "מַפָּאוּת" },
    { foreign: "קְרֵאָטִיבִי", hebrew: "יְצִירָתִי" },
    { foreign: "קְרֵאָטִיבִיּוֹת", hebrew: "יְצִירָתִיּוּת" },
    { foreign: "קְרִיטִיקָה", hebrew: "בִּקֹּרֶת" },
    { foreign: "קְרִימִינָל", hebrew: "פּוֹשֵׁעַ" },
    { foreign: "קְרִיסְטָל", hebrew: "בְּדֹלַח" },
    { foreign: "תֵּאוֹרֵטִי", hebrew: "עִיּוּנִי" },
    { foreign: "תֵּאוֹרְיָה", hebrew: "תּוֹרָה" },
    { foreign: "תֵּזָאוּרוּס", hebrew: "אַגְרוֹן" },
    { foreign: "תִּימִין", hebrew: "קוֹרָנִית" },
    { foreign: "תֵּמָה", hebrew: "נוֹשֵׂא" },
    { foreign: "תְּרוֹמְבּוֹצִיט", hebrew: "טַסִּית דָּם" },
    { foreign: "תֶּרְמוֹגְרַפְיָה", hebrew: "רִשּׁוּם חֹם" },
    { foreign: "תֶּרְמוֹמֶטֶר", hebrew: "מַדְחֹם" },
    { foreign: "תֶּרְמוֹס", hebrew: "שְׁמַרְחֹם" },
    { foreign: "תֶּרְמוֹסְטָט", hebrew: "וַסַּת חֹם" },
    { foreign: "תֶּרְמִי", hebrew: "חֻמָּנִי" },
    { foreign: "רִיל טַיְם", hebrew: "זְמַן אֱמֶת" },
    { foreign: "רִילוֹקֶיְשֶׁן", hebrew: "עִתּוּק" },
    { foreign: "רִינְגְּטוֹן", hebrew: "נְעִימוֹן" },
    { foreign: "רִיף", hebrew: "שׁוּנִית" },
    { foreign: "רִיצְ'רָץ'", hebrew: "רוֹכְסַן" },
    { foreign: "רִיתְמוּס", hebrew: "מִקְצָב" },
    { foreign: "רֶכֶב הִיבְּרִידִי", hebrew: "רֶכֶב כִּלְאַיִם" },
    { foreign: "רֵלָטִיבִי", hebrew: "יַחֲסִי" },
    { foreign: "רֵלִיגְיוֹזִי", hebrew: "דָּתִי" },
    { foreign: "רֵלִיגְיוֹזִיּוֹת", hebrew: "דָּתִיּוּת" },
    { foreign: "רַמְפָּה", hebrew: "כֶּבֶשׁ" },
    { foreign: "רַנְדּוֹמָלִי", hebrew: "אַקְרָאִי" },
    { foreign: "רֶסְטוֹרַצְיָה", hebrew: "שִׁחְזוּר" },
    { foreign: "רסיבר", hebrew: "מַקְלֵט" },
    { foreign: "רֶסְפֵּקְט", hebrew: "כָּבוֹד" },
    { foreign: "רֶפְּטִיטִיבִּי", hebrew: "חָזַרְתִּי" },
    { foreign: "רֶפְּרֵזֶנְטָטִיבִי", hebrew: "יִצּוּגִי" },
    { foreign: "רַצְיוֹנָלִי", hebrew: "שְׂכַלְתָּנִי" },
    { foreign: "רַצְיוֹנָלִיּוּת", hebrew: "שְׂכַלְתָּנוּת" },
    { foreign: "רַצְיוֹנָלִיסְט", hebrew: "שְׂכַלְתָּן" },
    { foreign: "רֵצֵסִיבִי", hebrew: "נַסְגָנִי" },
    { foreign: "רֵצֵפְּט", hebrew: "מִרְשָׁם" },
    { foreign: "רֵקוֹרְד", hebrew: "שִׂיא" },
    { foreign: "רֵקוֹרְסִיבִי", hebrew: "נָסוֹג" },
    { foreign: "רקלמה", hebrew: "פִּרְסֹמֶת" },
    { foreign: "של", hebrew: "רְדִיד" },
    { foreign: "שלאגר", hebrew: "לָהִיט" },
    { foreign: "שלוקר", hebrew: "חֵמֶת" },
    { foreign: "שַׁלְטֶר", hebrew: "מַפְסֵק" },
    { foreign: "שלייקס", hebrew: "כְּתֵפוֹת" },
    { foreign: "שַׁמְפּוּ", hebrew: "תַּחְפִּיף" },
    { foreign: "שְׁנוֹרְקֶל", hebrew: "צַנְרָן" },
    { foreign: "שְׁנִיצֶל", hebrew: "כְּתִיתָה" },
    { foreign: "שֵׁף", hebrew: "אַשָּׁף" },
    { foreign: "שְׁפִּיץ", hebrew: "חֹד" },
    { foreign: "שְׁפַּכְטֵל", hebrew: "מָרִית" },
    { foreign: "שְׁרִימְפ", hebrew: "חֲסִילוֹן" },
    { foreign: "לַנְג'", hebrew: "מִכְרָע" },
    { foreign: "לַבּוֹרַנְט", hebrew: "מַעְבָּדָן" },
    { foreign: "לבירינת", hebrew: "מָבוֹךְ" },
    { foreign: "לגלי", hebrew: "חֻקִּי" },
    { foreign: "לגנדה", hebrew: "אַגָּדָה" },
    { foreign: "לוֹאוֹ קוסט", hebrew: "טִיסַת חֶסֶךְ" },
    { foreign: "לוֹבִּיסְט", hebrew: "שַׁדְלָן" },
    { foreign: "לוֹגוֹ", hebrew: "סַמְלִיל" },
    { foreign: "לוֹגִי", hebrew: "הֶגְיוֹנִי" },
    { foreign: "לָוֶנְדֵר", hebrew: "אֲזוֹבְיוֹן" },
    { foreign: "לוֹיָאלִי", hebrew: "נֶאֱמָן" },
    { foreign: "לוֹיָאלִיּוֹת", hebrew: "נֶאֱמָנוּת" },
    { foreign: "לוּף", hebrew: "קְצִיץ" },
    { foreign: "לוֹקָלִי", hebrew: "מְקוֹמִי" },
    { foreign: "לוּקְסוּס", hebrew: "מוֹתָרוֹת" },
    { foreign: "לטקס", hebrew: "לְבִיבוֹת" },
    { foreign: "לִיבֶּרְטְרִיָּאנִיזְם", hebrew: "חֵרוּתָנוּת" },
    { foreign: "לִיבֵּרָלִיזְם", hebrew: "חֵרוּתִיּוֹת" },
    { foreign: "לִיטֵרָלִי", hebrew: "מִלּוּלִי" },
    { foreign: "לַיְן־אַפְּ", hebrew: "תַּסְדִּיר" },
    { foreign: "לַיְסְט", hebrew: "פְּסִיס" },
    { foreign: "לִימִינָלִי", hebrew: "סִפִּי" },
    { foreign: "לִימִינָלִיּוּת", hebrew: "סִפִּיּוֹת" },
    { foreign: "לִינְגְּוִיסְטִיקָה", hebrew: "בַּלְשָׁנוּת" },
    { foreign: "לִינוֹלֵאוּם", hebrew: "שַׁעֲמָנִית" },
    { foreign: "לְקֵסִיקוֹלוֹגְיָה", hebrew: "מִלּוֹנוּת" },
    { foreign: "לֶקְסִיקָלִי", hebrew: "מִלּוֹנִי" },
    { foreign: "דַּאבֶּל", hebrew: "כָּפוּל" },
    { foreign: "דֵּאוֹדוֹרַנְט", hebrew: "אַל רֵיחַ" },
    { foreign: "דָּאטָה", hebrew: "נְתוּנִים" },
    { foreign: "דָּאטָה בְּיֵס", hebrew: "מַסַּד נְתוּנִים" },
    { foreign: "דֶּה יוּרֶה", hebrew: "לַהֲלָכָה" },
    { foreign: "דֶּה־לֵגִיטִימַצְיָה", hebrew: "הֲפָסְלָה" },
    { foreign: "דֶּה־פַקְטוֹ", hebrew: "לְמַעֲשֶׂה" },
    { foreign: "דּוּאֵט", hebrew: "דּוּאִית" },
    { foreign: "דּוּאָלִיּוּת", hebrew: "שְׁנִיּוֹת" },
    { foreign: "דּוֹלָה", hebrew: "תּוֹמֶכֶת לֵדָה" },
    { foreign: "דּוֹלִי", hebrew: "צְלַמְנוֹעַ" },
    { foreign: "דּוֹלִינָה", hebrew: "בּוֹלְעָן" },
    { foreign: "דומיין", hebrew: "תְּחוּם" },
    { foreign: "דונגל", hebrew: "תְּקִיעַ" },
    { foreign: "דופליקציה", hebrew: "הַכְפָּלָה" },
    { foreign: "דּוֹקוּמֵנְט", hebrew: "מִסְמָךְ" },
    { foreign: "דּוֹקוּמֶנְטָרִי", hebrew: "תִּעוּדִי" },
    { foreign: "דּוֹקְטְרִינָה", hebrew: "מִשְׁנֶה" },
    { foreign: "דוש", hebrew: "מַקְלֵחַ" },
    { foreign: "דֵּטֶרְמִינִיזְם", hebrew: "כָּרְחָנוּת" },
    { foreign: "דֵּטֶרְמִינִיסְטִי", hebrew: "כָּרְחָנִי" },
    { foreign: "דִּי־גֵ'יי", hebrew: "תַּקְלִיטָן" },
    { foreign: "דִּיאֵז", hebrew: "נָסֵק" },
    { foreign: "דִּיאֵטָן", hebrew: "תְּזוּנַאי" },
    { foreign: "דִּיאָלוֹג", hebrew: "דּוּ שִׂיחַ" },
    { foreign: "דִּיאָלֵקְט", hebrew: "לַהַג" },
    { foreign: "דִּיאַסְפּוֹרָה", hebrew: "פְּזוּרָה" },
    { foreign: "דִּיאַפְזוֹן", hebrew: "מִנְעַד" },
    { foreign: "דִּיבֵּיְט", hebrew: "מַעֲמָת" },
    { foreign: "דִּיבֶּל", hebrew: "מֵיתָד" },
    { foreign: "דִּיגִיטָלִי", hebrew: "סִפְרָתִי" },
    { foreign: "דִּיוִיזְיָה", hebrew: "אֻגְדָּה" },
    { foreign: "דְּיוּנָה", hebrew: "חוֹלִית" },
    { foreign: "דיז'סטיף", hebrew: "אֶפְטָר" },
    { foreign: "דיזיינר", hebrew: "מְעַצֵּב" },
    { foreign: "דיזרט", hebrew: "פַּרְפֶּרֶת" },
    { foreign: "דִּיל", hebrew: "עִסְקָה" },
    { foreign: "דילטנט", hebrew: "חוֹבְבָן" },
    { foreign: "דילטנטיות", hebrew: "חוֹבְבָנוּת" },
    { foreign: "דִּימֶר", hebrew: "עַמְעַם" },
    { foreign: "דִּיסוֹנַנְס", hebrew: "צְרִימָה" },
    { foreign: "דִּיסְטֶרְבֵּיוֹטוֹר", hebrew: "מַפְלֵג" },
    { foreign: "דִּיסִידֵנְט", hebrew: "פָּלִיג" },
    { foreign: "דִּיסִימִילַצְיָה", hebrew: "הִבָּדְלוּת" },
    { foreign: "דִּיסְק אוֹן קִי", hebrew: "הֶחְסֵן נַיָּד" },
    { foreign: "דיסקורס", hebrew: "שִׂיחַ" },
    { foreign: "דִּיסְקֵט", hebrew: "תַּקְלִיטוֹן" },
    { foreign: "דִּיפּ־סְטֵיְט", hebrew: "מְדִינַת צְלָלִים" },
    { foreign: "דיפו", hebrew: "קַרְפִּיף" },
    { foreign: "דִּיפוּזְיָה", hebrew: "פִּעְפּוּעַ" },
    { foreign: "דיפולט", hebrew: "בְּרֵרַת מֶחְדָּל" },
    { foreign: "דִּיפֵרֶנְצִיַּאצְיָה", hebrew: "בִּדּוּל" },
    { foreign: "דֵּמָגוֹגְיָה", hebrew: "מִלְּהִיגוֹת" },
    { foreign: "דֵּמוֹנְסְטֵרַצְיָה", hebrew: "הַפְגָּנָה" },
    { foreign: "דֵּמֶנְטִי", hebrew: "קַהֲיוֹנִי" },
    { foreign: "דֵּמֶנְסִיָּה", hebrew: "קֵהָיוֹן" },
    { foreign: "דֶּנְטִין", hebrew: "שֶׁנְהָב" },
    { foreign: "דֵּסְק", hebrew: "מָדוֹר" },
    { foreign: "דפיברילטור", hebrew: "מַפְעֵם" },
    { foreign: "יוּפִּיטֶר", hebrew: "צֶדֶק" },
    { foreign: "אֶקְסְפּוֹרְט", hebrew: "יְצוּא" },
    { foreign: "אקצנט", hebrew: "מִבְטָא" },
    { foreign: "אַקְרוֹבָּט", hebrew: "לוּלְיָן" },
    { foreign: "אֵרוֹבִּי", hebrew: "אֲוִירָנִי" },
    { foreign: "אָרוֹמָה", hebrew: "בְּשֹׂמֶת" },
    { foreign: "אַרְטִישׁוֹק", hebrew: "קִנְרָס" },
    { foreign: "אֵתִי", hebrew: "מוּסָרִי" },
    { foreign: "בָּאג", hebrew: "תֶּקֶל" },
    { foreign: "בָּאוּלִינְג", hebrew: "כַּדֹּרֶת" },
    { foreign: "בָּאז", hebrew: "רַחֶשֶׁת" },
    { foreign: "בָּאגָאז'", hebrew: "תָּא מִטְעָן" },
    { foreign: "בֶּדְמִינְטוֹן", hebrew: "נוֹצִית" },
    { foreign: "בּוּטְקָה", hebrew: "שׁוֹמֵרָה" },
    { foreign: "בּוּלְדּוֹזֶר", hebrew: "דַּחְפּוֹר" },
    { foreign: "בּוּלִימְיָה", hebrew: "זַלֶּלֶת" },
    { foreign: "בּוּנְקֶר", hebrew: "מִבְצוֹר" },
    { foreign: "בּוּפֶה", hebrew: "מִזְנוֹן" },
    { foreign: "בֻּרְגּוּל", hebrew: "רִיפוֹת" },
    { foreign: "בּוּרִי", hebrew: "קִיפוֹן" },
    { foreign: "בּוֹרְשְׁט", hebrew: "חֲמִיצָה" },
    { foreign: "בָּזִילִיקוּם", hebrew: "רֵיחָן" },
    { foreign: "בָּטָרִיָּה", hebrew: "סוֹלְלָה" },
    { foreign: "בִּיהֶבְיוֹרִיזְם", hebrew: "הִתְנַהֲגוּתָנוּת" },
    { foreign: "בִּיזְנֶס", hebrew: "עֵסֶק" },
    { foreign: "בייבי גרו", hebrew: "מִגְמֶשֶׁת" },
    { foreign: "בֶּיְבִּיסִיטֶר", hebrew: "שְׁמַרְטַף" },
    { foreign: "בֵּיְגְּל", hebrew: "כַּעַךְ" },
    { foreign: "בֶּיְסְבּוֹל", hebrew: "כַּדּוּר בָּסִיס" },
    { foreign: "בִּילְט אִין", hebrew: "מֻבְנֶה" },
    { foreign: "בִּילָטֵרָלִי", hebrew: "דּוּ צְדָדִי" },
    { foreign: "בִּיס", hebrew: "נְגִיסָה" },
    { foreign: "בִּיסְקְוִיט", hebrew: "מַרְקוֹעַ" },
    { foreign: "רוֹלָדָה", hebrew: "גָּלִילָה" },
    { foreign: "סְטֵיְק", hebrew: "אֻמְּצָה" },
    { foreign: "צִ'יפְּס", hebrew: "טֻגָּנִים" },
    { foreign: "אָאוּטֵלְט", hebrew: "חֲנוּת עֳדָפִים" },
    { foreign: "אָאוּטְסוֹרְסִינְג", hebrew: "מִקּוּר חוּץ" },
    { foreign: "אָאוּטְפּוּט", hebrew: "פֶּלֶט" },
    { foreign: "אַבְּסוֹלוּטִי", hebrew: "מֻחְלָט" },
    { foreign: "אַבְּסְטְרַקְט", hebrew: "תַּקְצִיר" },
    { foreign: "אַבְּסְטְרַקְטִי", hebrew: "מֻפְשָׁט" },
    { foreign: "אָגֶ'נְדָּה", hebrew: "סֵדֶר יוֹם" },
    { foreign: "אֵגוֹאִיזְם", hebrew: "אָנוֹכִיּוּת" },
    { foreign: "אֵגוֹאִיסְט", hebrew: "אָנוֹכִי" },
    { foreign: "אֶגְזוֹז", hebrew: "צִנּוֹר פְּלִיטָה" },
    { foreign: "אַגְרֵסִיבִי", hebrew: "תּוֹקְפָנִי" },
    { foreign: "אֶדְמִינְסְטְרָטִיבִי", hebrew: "מִנְהָלִי" },
    { foreign: "אָדַפְּטַצְיָה", hebrew: "הִסְתַּגְּלוּת" },
    { foreign: "אוֹבָלִי", hebrew: "סְגַלְגַּל" },
    { foreign: "אוֹבְּסֵסִיבִי", hebrew: "טִרְדּוֹנִי" },
    { foreign: "אוֹבְּסֶסְיָה", hebrew: "טֵרָדוֹן" },
    { foreign: "אוֹבֶרְדְּרַפְט", hebrew: "מְשִׁיכַת יֶתֶר" },
    { foreign: "אוֹדְיוֹ", hebrew: "שֵׁמַע" },
    { foreign: "אוֹדִישֶׁן", hebrew: "מִבְחַן בָּמָה" },
    { foreign: "אווטר", hebrew: "יַצְּגָן" },
    { foreign: "אוֹטוֹנוֹמְיָה", hebrew: "מִמְשָׁל עַצְמִי" },
    { foreign: "אוֹטוֹסְטְרָדָה", hebrew: "דֶּרֶךְ מְהִירָה" },
    { foreign: "אוּלְטְרָה סָגֹל", hebrew: "עַל סָגֹל" },
    { foreign: "אוֹלִיגַרְכִיָּה", hebrew: "שִׁלְטוֹן קֹמֶץ" },
    { foreign: "אֻמְלַט", hebrew: "חֲבִיתָה" },
    { foreign: "אוֹנוֹמָטוֹפֵּאָה", hebrew: "תַּצְלִיל" },
    { foreign: "אוֹנְלַיְן", hebrew: "מְקֻוָּן" },
    { foreign: "אוֹסְמוֹזָה", hebrew: "פִּעְפּוּעַ" },
    { foreign: "אוֹפּוֹזִיצְיָה", hebrew: "נֶגְדָה" },
    { foreign: "אוֹפּוֹרְטוּנִיזְם", hebrew: "הִזְדַּמְנַנּוּת" },
    { foreign: "אוֹפְּטִימוּם", hebrew: "מֵיטַב" },
    { foreign: "אוֹפְּטִימִיזַצְיָה", hebrew: "מִטּוּב" },
    { foreign: "אוֹפְּטִימָלִי", hebrew: "מֵיטָבִי" },
    { foreign: "אוֹפֶנְסִיבָה", hebrew: "מִתְקָפָה" },
    { foreign: "אוֹפְסַיְד", hebrew: "נִבְדָּל" },
    { foreign: "אוֹקְטָגוֹן", hebrew: "מְתֻמָּן" },
    { foreign: "אוֹקְסִימוֹרוֹן", hebrew: "נִיב נִגּוּדִים" },
    { foreign: "אוּרְבָּנִי", hebrew: "עִירוֹנִי" },
    { foreign: "אורגנו", hebrew: "אֲזוֹבִית" },
    { foreign: "אוֹרְגָּנִיזְם", hebrew: "יְצוּר" },
    { foreign: "אֵטִימוֹלוֹגְיָה", hebrew: "גִּזָּרוֹן" },
    { foreign: "אטצ'מנט", hebrew: "צְרוּפָה" },
    { foreign: "אַטְרַקְטִיבִי", hebrew: "מוֹשֵׁךְ" },
    { foreign: "אִידְיוֹם", hebrew: "נִיב" },
    { foreign: "אַי קְיוּ", hebrew: "מְנַת מִשְׂכָּל" },
    { foreign: "אַיְטֵם", hebrew: "פְּרִיט" },
    { foreign: "אִילוּזְיָה", hebrew: "אַשְׁלָיָה" },
    { foreign: "אימג'", hebrew: "תְּמוּנָה" },
    { foreign: "אִימוּגִ'י", hebrew: "סִמְלוֹן" },
    { foreign: "אֵמִיגְרַצְיָה", hebrew: "הֲגִירָה" },
    { foreign: "אימייל", hebrew: "דֹּאַר אֵלֶקְטְרוֹנִי" },
    { foreign: "אִימְפּוּלְסִיבִי", hebrew: "פַּרְצָנִי" },
    { foreign: "אִימְפּוֹרְט", hebrew: "יְבוּא" },
    { foreign: "אִימְפֵּטִיגוֹ", hebrew: "גַּלֶּדֶת" },
    { foreign: "אִימְפְּרוֹבִיזַצְיָה", hebrew: "אִלְתּוּר" },
    { foreign: "אינג'יניר", hebrew: "מְהַנְדֵּס" },
    { foreign: "אִינְדִּיפֵרֶנְטִי", hebrew: "אָדִישׁ" },
    { foreign: "אינדקס", hebrew: "מַדָּד" },
    { foreign: "אִינְטֶגְרִיטִי", hebrew: "יָשְׁרָה" },
    { foreign: "אִינְטוֹנַצְיָה", hebrew: "הַנְגָּנָה" },
    { foreign: "טונר", hebrew: "מַחְסָנִית דְּיוֹ" },
    { foreign: "טוֹסְט", hebrew: "לֶחֶם קָלוּי" },
    { foreign: "טוֹסְטֵר", hebrew: "מַצְנֵם" },
    { foreign: "טוֹסְטֵר אוֹבֵן", hebrew: "תַּנּוּרוֹן" },
    { foreign: "טוֹקְבֶּק", hebrew: "תְּגוּבִית" },
    { foreign: "טוֹקְבֵּקִיסְט", hebrew: "תְּגוּבָן" },
    { foreign: "טוקסין", hebrew: "רַעֲלָן" },
    { foreign: "טוּרְבָּן", hebrew: "צָנִיף" },
    { foreign: "טוּשׁ", hebrew: "מַצְבֵּעַ" },
    { foreign: "טטנוס", hebrew: "צַפֶּדֶת" },
    { foreign: "טַיְמִינְג", hebrew: "תִּזְמוּן" },
    { foreign: "טַיְמֵר", hebrew: "קוֹצֵב זְמַן" },
    { foreign: "טֵיְפּ", hebrew: "רְשַׁמְקוֹל" },
    { foreign: "טַיְץ", hebrew: "צְמוּדוֹנִים" },
    { foreign: "טֵיְק אוויי", hebrew: "קַח וָלֵךְ" },
    { foreign: "טַיְקוּן", hebrew: "אֵיל הוֹן" },
    { foreign: "טִילְדָּה", hebrew: "גַּל" },
    { foreign: "טִיפּ", hebrew: "תֶּשֶׁר" },
    { foreign: "טִיפֵּקְס", hebrew: "מְחִיקוֹן" },
    { foreign: "טִיק", hebrew: "פִּרְכּוּס" },
    { foreign: "טִישׁוּ", hebrew: "מַלְמָלִית" },
    { foreign: "טֶכְנוֹקְרַטְיָה", hebrew: "שִׁלְטוֹן מֻמְחִים" },
    { foreign: "טֵלֶגְרָמָה", hebrew: "מִבְרָק" },
    { foreign: "טֶלֶר", hebrew: "כְּסֵפֶר" },
    { foreign: "טַמְבּוֹן", hebrew: "פָּגוֹשׁ" },
    { foreign: "טֶמְפּוֹ", hebrew: "מִפְעָם" },
    { foreign: "טֶמְפֵּרָמֶנְט", hebrew: "מֶזֶג" },
    { foreign: "טֶנְדֵּר", hebrew: "מִטְעָנִית" },
    { foreign: "טֶקְסְטוּרָה", hebrew: "מִרְקָם" },
    { foreign: "טַקְסִי", hebrew: "מוֹנִית" },
    { foreign: "טְרָאוּמָה", hebrew: "חוֹבְלָה" },
    { foreign: "טְרָאוּמָטִי", hebrew: "חוֹבְלָנִי" },
    { foreign: "טרגוט", hebrew: "קִיהוּל" },
    { foreign: "טְרִיבּוּנָל", hebrew: "בֵּית דִּין" },
    { foreign: "טְרִיגֶר", hebrew: "מַזְנֵק" },
    { foreign: "טֵרִיטוֹרְיָאלִי", hebrew: "תְּחוּמָתִי" },
    { foreign: "טֵרִיטוֹרְיָאלִיּוֹת", hebrew: "תְּחוּמָתִיּוּת" },
    { foreign: "טריידר", hebrew: "סַחֲרָן" },
    { foreign: "טְרֵיְלֶר", hebrew: "גָּרוֹר" },
    { foreign: "טֶרְמִינוֹלוֹגְיָה", hebrew: "מִנּוּחַ" },
    { foreign: "טֶרְמִינָל", hebrew: "מָסוֹף" },
    { foreign: "טְרַמְפּוֹלִינָה", hebrew: "קַפֶּצֶת" },
    { foreign: "טְרֵנִינְג", hebrew: "אִמּוּנִית" },
    { foreign: "טְרַנְסְפּוֹרְט", hebrew: "תּוֹבָלָה" },
    { foreign: "טְרַנְסְפּוֹרְטֵר", hebrew: "מוֹבִיל" },
    { foreign: "טְרַנְסְפוֹרְמָטוֹר", hebrew: "שַׁנַּאי" },
    { foreign: "טְרַנְסְפוֹרְמַצְיָה", hebrew: "הַתְמָרָה" },
    { foreign: "טֵרָסָה", hebrew: "מַדְרֵגָה" },
    { foreign: "טְשׁוּלְנְט", hebrew: "חַמִּין" },
    { foreign: "פָּאוּץ'", hebrew: "פֻּנְדָּה" },
    { foreign: "פָּזֶל", hebrew: "תַּצְרֵף" },
    { foreign: "פַּאי", hebrew: "תַּמְלִיא" },
    { foreign: "פַּאנְץ' לַיְן", hebrew: "שׁוּרַת מַחַץ" },
    { foreign: "פַּרְטִי פּוֹפֶּר", hebrew: "מַשְׁבִּית שְׂמָחוֹת" },
    { foreign: "פֵּדָל", hebrew: "דַּוְשָׁה" },
    { foreign: "פֵּדַנְט", hebrew: "נוֹקְדָן" },
    { foreign: "פוֹבְּיָה", hebrew: "בַּעַת" },
    { foreign: "פּוֹדְיוּם", hebrew: "דּוּכַן מְנַצְּחִים" },
    { foreign: "פּוּדִינְג", hebrew: "רַפְרֶפֶת" },
    { foreign: "פּוֹדְפֵרוֹסְסוֹר", hebrew: "מְעַבֵּד מָזוֹן" },
    { foreign: "פּוֹדְקַאסְט", hebrew: "הֶסְכֵּת" },
    { foreign: "פּוֹזִיטִיבִי", hebrew: "חִיּוּבִי" },
    { foreign: "פוֹטוֹגְרַפְיָה", hebrew: "צִלּוּם" },
    { foreign: "פוֹטוֹמוֹנְטָז'", hebrew: "תְּמוּנָה מְשֻׁבֶּצֶת" },
    { foreign: "פוֹטוֹסִינְתֵּזָה", hebrew: "הַטְמָעַת אוֹר" },
    { foreign: "פּוֹטֶנְצְיָאל", hebrew: "יָכְלָה" },
    { foreign: "פּוּטְשׁ", hebrew: "הֲפִיכָה" },
    { foreign: "פוינטר", hebrew: "מַצְבִּיעַ" },
    { foreign: "פּוֹלִיגוֹן", hebrew: "מְצֻלָּע" },
    { foreign: "פּוֹלִיגְרָף", hebrew: "גַּלַּאי שֶׁקֶר" },
    { foreign: "פּוֹלְיוֹ", hebrew: "שִׁתּוּק יְלָדִים" },
    { foreign: "פּוֹלִיטִיקְלִי קוֹרֵקְט", hebrew: "תַּקִּין פּוֹלִיטִית" },
    { foreign: "אַנְתְּרַקְס", hebrew: "גַּחֶלֶת" },
    { foreign: "אֵס-אֵם-אֵס", hebrew: "מִסְרוֹן" },
    { foreign: "אָסִיסְטֵנְט", hebrew: "סַיָּע" },
    { foreign: "אַסְפִּירַצְיָה", hebrew: "שְׁאִיפָה" },
    { foreign: "אַסְפֵּקְט", hebrew: "הֶבֵּט" },
    { foreign: "אסקלציה", hebrew: "הַסְלָמָה" },
    { foreign: "אסקפיזם", hebrew: "בּוֹרְחָנוּת" },
    { foreign: "אַסְתְּמָה", hebrew: "קַצֶּרֶת" },
    { foreign: "אַפְטֶר", hebrew: "חָפְשׁוֹן" },
    { foreign: "אֵפִּידֶמְיָה", hebrew: "מַגֵּפָה" },
    { foreign: "אֶפִּילֶפְּסִיָּה", hebrew: "כִּפְיוֹן" },
    { foreign: "אַפְּלִיקַצְיָה", hebrew: "יִשּׂוּמוֹן" },
    { foreign: "אַפֶּנְדִּיצִיט", hebrew: "תּוֹסֶפְתָּן" },
    { foreign: "אַפֵּרִיטִיף", hebrew: "אַקְדָּם" },
    { foreign: "אַפַּתְיָה", hebrew: "אִדָּשׁוֹן" },
    { foreign: "אַקְוֵדוּקְט", hebrew: "אַמַּת מַיִם" },
    { foreign: "אַקְוִיפֵר", hebrew: "אַקְוָה" },
    { foreign: "אַקְוִילֶיְזֶר", hebrew: "שַׁוְיָן" },
    { foreign: "אֵקוֹנוֹמִי", hebrew: "כַּלְכָּלִי" },
    { foreign: "אָקוֹרְד", hebrew: "תַּצְלִיל" },
    { foreign: "אָקוֹרְדְּיוֹן", hebrew: "מַפּוּחוֹן" },
    { foreign: "אֶקְזִיט", hebrew: "הֶנְפֵּק" },
    { foreign: "אֶקְזִיסְטַצְיָאלִי", hebrew: "קִיּוּמִי" },
    { foreign: "אֶקְזֵמָה", hebrew: "גָּרָב" },
    { foreign: "אַקְטִיבִי", hebrew: "פָּעִיל" },
    { foreign: "אַקְטִיבִיזְם", hebrew: "פְּעִילָנוּת" },
    { foreign: "אקנה", hebrew: "חַטֶּטֶת" },
    { foreign: "אֶקְסְפּוֹנֶנְצִיָּאלִי", hebrew: "מַעֲרִיכִי" },
    { foreign: "רֵבוֹלוּצְיָה", hebrew: "מַהְפֵּכָה" },
    { foreign: "רָדָאר", hebrew: "מַכָּם" },
    { foreign: "רַדְיוּס", hebrew: "חִשּׁוּר" },
    { foreign: "רָדִיקָלִיזְם", hebrew: "קִיצוֹנִיּוּת" },
    { foreign: "רֵוֵרְס", hebrew: "הִלּוּךְ אֲחוֹרִי" },
    { foreign: "רוּטִינָה", hebrew: "שִׁגְרָה" },
    { foreign: "רוטיני", hebrew: "שִׁגְרָתִי" },
    { foreign: "רוֹטַצְיָה", hebrew: "סֶבֶב" },
    { foreign: "רֵזוּמֶה", hebrew: "קוֹרוֹת חַיִּים" },
    { foreign: "רֵזֶרְבָה", hebrew: "עֲתוּדָה" },
    { foreign: "רֶטְרוֹסְפֶּקְטִיבִי", hebrew: "אֲחוֹרָנִי" },
    { foreign: "רֵאַלְיָה", hebrew: "מְצִיאוּת" },
    { foreign: "רֵאָלִיזְם", hebrew: "מְצִיאוּתָנוּת" },
    { foreign: "רֵאָלִיסְט", hebrew: "מְצִיאוּתָנִי" },
    { foreign: "רֵאַקְצִיָּה", hebrew: "תְּגוּבָה" },
    { foreign: "רִיבָּאוּנְד", hebrew: "כַּדּוּר נִתָּר" },
    { foreign: "רֶיְטִינְג", hebrew: "מִדְרוּג" },
    { foreign: "אִינְטֶנְסִיבִי", hebrew: "עָצִים" },
    { foreign: "אִינְטֶרְאַקְטִיבִי", hebrew: "הִדּוּדִי" },
    { foreign: "אִינְטֶרְדִּיסְצִיפְּלִינִי", hebrew: "בֵּין תְּחוּמִי" },
    { foreign: "אִינְטֶרְנֶט", hebrew: "מִרְשֶׁתֶת" },
    { foreign: "אִינְטֶרְנַצְיוֹנָלִי", hebrew: "בֵּין לְאֻמִּי" },
    { foreign: "אינסטלטור", hebrew: "שְׁרַבְרַב" },
    { foreign: "אִינְסַיְט", hebrew: "תּוֹבָנָה" },
    { foreign: "אִינְפוּזְיָה", hebrew: "עֵרוּי" },
    { foreign: "אִינְפּוּט", hebrew: "קֶלֶט" },
    { foreign: "אִינְפוֹרְמַצְיָה", hebrew: "מֵידָע" },
    { foreign: "אִינְפֶקְצִיָּה", hebrew: "זִהוּם" },
    { foreign: "אִינְקוּבָּטוֹר", hebrew: "חֲמָמָית" },
    { foreign: "אִינְקוֹגְנִיטוֹ", hebrew: "בְּעִלּוּם שֵׁם" },
    { foreign: "אינקונבולה", hebrew: "דְּפוּס עֶרֶשׂ" },
    { foreign: "אִינֶרְצִיָּה", hebrew: "הֶתְמֵד" },
    { foreign: "אוֹפוֹרְיָה", hebrew: "זְחִיחוּת" },
    { foreign: "אָכִינְצֵאָה", hebrew: "קִפּוֹדָנִית" },
    { foreign: "אַלְטְרוּאִיזְם", hebrew: "זוּלָתָנוּת" },
    { foreign: "אַלְטְרוּאִיסְט", hebrew: "זוּלָתָנִי" },
    { foreign: "אַלְטֶרְנָטִיבָה", hebrew: "חֲלוּפָה" },
    { foreign: "אַלְטֶרְנָטִיבִי", hebrew: "חֲלוּפִי" },
    { foreign: "אֵלִיטָה", hebrew: "עִלִּית" },
    { foreign: "אֵלִיטִיסְטִי", hebrew: "עִלִּיתַנִי" },
    { foreign: "אֵלִיפְּסִיס", hebrew: "הֶשְׁמֵט" },
    { foreign: "אָלֶרְגִּי", hebrew: "רִגְשָׁתִי" },
    { foreign: "אָלֶרְגִּיָּה", hebrew: "רַגֶּשֶׁת" },
    { foreign: "אַמְבּוּשׁ", hebrew: "מַאֲרָב" },
    { foreign: "אַמְבִּיצְיוֹנֵר", hebrew: "שְׁאַפְתָּן" },
    { foreign: "אֶמְבַּרְגּוֹ", hebrew: "הֶחְסֵם" },
    { foreign: "אֵמוּלְסִיָּה", hebrew: "תַּחְלִיב" },
    { foreign: "אֵמִיגְרַנְט", hebrew: "מְהַגֵּר" },
    { foreign: "אֵמִיגְרַצְיָה", hebrew: "הֲגִירָה" },
    { foreign: "אַמְנֶזְיָה", hebrew: "שִׁכָּחוֹן" },
    { foreign: "אַמְפּוּלָה", hebrew: "בַּקְבּוּקִית" },
    { foreign: "אֶמְפִּירִי", hebrew: "נַסּוֹתִי" },
    { foreign: "אֶנְדּוֹסְקוֹפּ", hebrew: "מַשְׁקֵף" },
    { foreign: "אַנְדֶּרְדּוֹג", hebrew: "דַּל סִכּוּי" },
    { foreign: "אַנְדְּרוֹגִינִי", hebrew: "דּוּ מִינִי" },
    { foreign: "אָנוֹנִימִי", hebrew: "עֲלוּם שֵׁם" },
    { foreign: "אָנוֹרֶקְטִי", hebrew: "צַיְמָן" },
    { foreign: "אָנוֹרֶקְסִיָּה", hebrew: "צַיְמָנוּת" },
    { foreign: "אַנְטִיגֵן", hebrew: "אנגד" },
    { foreign: "אַנְטֵנָה", hebrew: "מְשׁוֹשָׁה" },
    { foreign: "אֵנִיגְמָטִי", hebrew: "חִידָתִי" },
    { foreign: "אָנִימַצְיָה", hebrew: "הַנְפָּשָׁה" },
    { foreign: "אַנְשׁוֹבִי", hebrew: "עַפְיָן" },
    { foreign: "מאלט", hebrew: "לֶתֶת" },
    { foreign: "מאפין", hebrew: "מוּפִין" },
    { foreign: "מַארְס", hebrew: "מַאְדִּים" },
    { foreign: "מֵגָלוֹמַנְיָה", hebrew: "שִׁגְעוֹן גַּדְלוּת" },
    { foreign: "מֵדִיטַצְיָה", hebrew: "בּוֹנְנוּת" },
    { foreign: "מֵדַלְיוֹן", hebrew: "תִּלְיוֹן" },
    { foreign: "מוֹבִּילִיּוּת", hebrew: "נַיָּדוּת" },
    { foreign: "מוֹדָה", hebrew: "אָפְנָה" },
    { foreign: "מוֹדוּלַצְיָה", hebrew: "אִפְנוּן" },
    { foreign: "מוֹדוּס אוֹפֵּרַנְדִּי", hebrew: "שִׁיטַת פְּעֻלָּה" },
    { foreign: "מוֹדֶרְנִי", hebrew: "חָדִישׁ" },
    { foreign: "מוזאיקה", hebrew: "פְּסֵיפָס" },
    { foreign: "מוֹטוֹר", hebrew: "מָנוֹעַ" },
    { foreign: "מוֹטִיבַצְיָה", hebrew: "הֲנִיעָה" },
    { foreign: "מוֹטֵל", hebrew: "מְלוֹנִית" },
    { foreign: "מוּטַצְיָה", hebrew: "תַּשְׁנִית" },
    { foreign: "מוּלְטִידִיסְצִיפְּלִינְרִי", hebrew: "רַב תְּחוּמִי" },
    { foreign: "מוּלְטִיפוֹקָל", hebrew: "רַב מוֹקְדִי" },
    { foreign: "מוּמְיָה", hebrew: "חָנוּט" },
    { foreign: "מוֹנוֹטוֹנִי", hebrew: "חַדְגּוֹנִי" },
    { foreign: "מוֹנוֹטוֹנִיּוּת", hebrew: "חַדְגּוֹנִיּוּת" },
    { foreign: "מוֹנוֹלוֹג", hebrew: "חַד שִׂיחַ" },
    { foreign: "מוֹנִיטוֹר", hebrew: "צָג" },
    { foreign: "מוּנִיצִיפָּלִי", hebrew: "עִירוֹנִי" },
    { foreign: "מוֹנַרְכִיזְם", hebrew: "מְלוּכָנוּת" },
    { foreign: "מוֹנַרְכִיָּה", hebrew: "מְלוּכָה" },
    { foreign: "מוּס", hebrew: "קְצִיפָה" },
    { foreign: "טאב", hebrew: "לְשׁוֹנִית" },
    { foreign: "טַאבּוּ", hebrew: "מִרְשַׁם מְקַרְקְעִין" },
    { foreign: "טַבְּלֶט", hebrew: "מַחְשֵׁב לוּחַ" },
    { foreign: "טַבּוּלָה רסה", hebrew: "לוּחַ חָלָק" },
    { foreign: "טוֹטַל לוֹס", hebrew: "אָבְדָן גָּמוּר" },
    { foreign: "טוֹטָלִיטָרִי", hebrew: "לוֹפְתָנִי" },
    { foreign: "טוֹטָלִיטָרִיזְם", hebrew: "לוֹפְתָנוּת" },
    { foreign: "טוֹלֵרַנְטִיּוּת", hebrew: "סוֹבְלָנוּת" },
    { foreign: "טוֹנוּס", hebrew: "מֶתַח שְׁרִירִים" },
    { foreign: "טוֹנִיקָה", hebrew: "יַרְכִּית" },
    { foreign: "פּוֹלִיסֵמִי", hebrew: "רַב מַשְׁמָעִי" },
    { foreign: "פּוֹלִיפוֹנִי", hebrew: "רַב קוֹלִי" },
    { foreign: "פּוֹלִיפוֹנְיָה", hebrew: "רַב קוֹלִיּוֹת" },
    { foreign: "פּוּלְס", hebrew: "דֹּפֶק" },
    { foreign: "פּוֹלָרִי", hebrew: "קָטְבִּי" },
    { foreign: "פּוֹלָרִיזַצְיָה", hebrew: "קִטּוּב" },
    { foreign: "פּוֹמְפָּה", hebrew: "פַּמְפֶּמֶת" },
    { foreign: "פומפון", hebrew: "פִּיף" },
    { foreign: "פונדמנטלי", hebrew: "יְסוֹדָנִי" },
    { foreign: "פוּנְדָּמֶנְטָלִיזְם", hebrew: "יְסוֹדָנוּת" },
    { foreign: "פוֹנְט", hebrew: "גּוֹפָן" },
    { foreign: "פוֹנֵמָה", hebrew: "הַגְיָן" },
    { foreign: "פוּנְקְצִיּוֹנָלִי", hebrew: "תִּפְקוּדִי" },
    { foreign: "פוּנְקְצְיוֹנָלִיזְם", hebrew: "תִּפְקוּדָנוּת" },
    { foreign: "פּוֹסְט", hebrew: "רְשׁוּמָה" },
    { foreign: "פּוֹסְטָה", hebrew: "דֹּאַר" },
    { foreign: "פּוֹסְטֶר", hebrew: "כְּרָזָה" },
    { foreign: "פוספור", hebrew: "זַרְחָן" },
    { foreign: "פּוֹפּ אַפּ", hebrew: "חַלּוֹן צָץ" },
    { foreign: "פּוֹפּוּלִיזְם", hebrew: "הֲמוּנָאוֹת" },
    { foreign: "פּוֹפְּקוֹרְן", hebrew: "פִּצְפּוּצֵי תִּירָס" },
    { foreign: "פּוֹרְטְפוֹלְיוֹ", hebrew: "תִּיק עֲבוֹדוֹת" },
    { foreign: "פּוֹרְטְרֵט", hebrew: "דְּיוֹקָן" },
    { foreign: "פּוּרִיזְם", hebrew: "טַהֲרָנוּת" },
    { foreign: "פוֹרִיסְט", hebrew: "טַהֲרָן" },
    { foreign: "פוֹרֵל", hebrew: "טְרוּטָה" },
    { foreign: "פוֹרְמָלִי", hebrew: "רִשְׁמִי" },
    { foreign: "פוּרְנִיר", hebrew: "קְלִיף" },
    { foreign: "פורס מָז'וֹר", hebrew: "כּוֹחַ עֶלְיוֹן" },
    { foreign: "פּוֹרְצֵלָן", hebrew: "חַרְסִינָה" },
    { foreign: "פטיציה", hebrew: "עֲצוּמָה" },
    { foreign: "פָטָלִי", hebrew: "גּוֹרָלִי" },
    { foreign: "פָּטֵפוֹן", hebrew: "מָקוֹל" },
    { foreign: "פַּטְרִיאַרְכָלִי", hebrew: "אַבְהָתָנִי" },
    { foreign: "פַּטְרִיאַרְכָלִיּוּת", hebrew: "אַבְהָתָנוּת" },
    { foreign: "פַּטְרִיּוֹט", hebrew: "מוֹלַדְתָּן" },
    { foreign: "פַּטְרִיּוֹטִיזְם", hebrew: "מוֹלַדְתָּנוּת" },
    { foreign: "פִּיגָ'מָה", hebrew: "חֲלִיפַת שֵׁנָה" },
    { foreign: "פִּיגְמֵנְט", hebrew: "צִבְעָן" },
    { foreign: "פִידְבֶּק", hebrew: "מָשׁוֹב" },
    { foreign: "פְיוּז", hebrew: "נָתִיךְ" },
    { foreign: "פייסר", hebrew: "מַכְתִּיב קֶצֶב" },
    { foreign: "פַּיְפּ", hebrew: "מִקְטֶרֶת" },
    { foreign: "פֵּיְק נְיוּז", hebrew: "חַדְשׁוֹת כָּזָב" },
    { foreign: "פיירוול", hebrew: "חוֹמַת אֵשׁ" },
    { foreign: "פילבוקס", hebrew: "מְצָדִית" },
    { foreign: "פִילְטֶר", hebrew: "מַסְנֵן" },
    { foreign: "פִילִיבַּסְטֶר", hebrew: "נְאוּם הַתָּשָׁה" },
    { foreign: "פִיקְצִיָּה", hebrew: "מִבְדֶּה" },
    { foreign: "פיקשן", hebrew: "בִּדְיוֹן" },
    { foreign: "פִּירָאט", hebrew: "שׁוֹדֵד יָם" },
    { foreign: "פִּירֶה", hebrew: "מָחִיתָ" },
    { foreign: "פִּירוֹמָן", hebrew: "מַצִּיתָן" },
    { foreign: "פִּירְסִינְג", hebrew: "נִזּוּם" },
    { foreign: "פְּלָאג", hebrew: "מַצָּת" },
    { foreign: "פָּלִינְדְּרוֹם", hebrew: "מִלָּה מִתְהַפֶּכֶת" },
    { foreign: "פֵּלִיקָן", hebrew: "שַׂקְנַאי" },
    { foreign: "פְלִירְט", hebrew: "אֲהַבְהַבִּים" },
    { foreign: "פְּלָנֵטָה", hebrew: "כּוֹכַב לֶכֶת" },
    { foreign: "פְּלַסְטֵלִינָה", hebrew: "טִינִית" },
    { foreign: "פְּלַסְטֵר", hebrew: "אִסְפְּלָנִית" },
    { foreign: "פְּלָצֶבּוֹ", hebrew: "תְּרוּפַת דֶּמֶה" },
    { foreign: "פֶּנְדֶּל", hebrew: "בְּעִיטַת עוֹנְשִׁין" },
    { foreign: "פֵנוֹמֵן", hebrew: "תּוֹפָעָה" },
    { foreign: "פֶּנְטָגוֹן", hebrew: "מְחֻמָּשׁ" },
    { foreign: "פֶּנְטְהָאוּס", hebrew: "דִּירַת גַּג" },
    { foreign: "פָּנִיקָה", hebrew: "תַּבְהֵלָה" },
    { foreign: "פֶּנְסִיּוֹן", hebrew: "בֵּית הַבְרָאָה" },
    { foreign: "פֶּנְסְיוֹנֵר", hebrew: "גִּמְלַאי" },
    { foreign: "פַּנְצֵ'ר", hebrew: "נֶקֶר" },
    { foreign: "פַּנְצֵ'ר מָאכֶער", hebrew: "צְמִיגַאי" },
    { foreign: "פַּנְצֵ'רִיָּה", hebrew: "צְמִיגִיָּה" },
    { foreign: "פַּנְקֵיְק", hebrew: "חֲמִיטָה" },
    { foreign: "פְּסוֹרְיָאזִיס", hebrew: "סַפַּחַת" },
    { foreign: "פָּסָז'", hebrew: "מִפְלָשׁ" },
    { foreign: "פַּסְטוֹרָלִיזְם", hebrew: "רוֹעִיּוֹת" },
    { foreign: "פָּסִיבִי", hebrew: "סָבִיל" },
    { foreign: "פָּסִיבִיּוּת", hebrew: "סְבִילוּת" },
    { foreign: "פָּסִיפְלוֹרָה", hebrew: "שְׁעוֹנִית" },
    { foreign: "פַּסְפּוֹרְט", hebrew: "דַּרְכּוֹן" },
    { foreign: "פַּפְּרִיקָה", hebrew: "פִּלְפֶּלֶת" },
    { foreign: "פַּצְפִּיזְם", hebrew: "שְׁלוֹמָנוּת" },
    { foreign: "פראק", hebrew: "מִכְנָף" },
    { foreign: "פֶּרְגּוּלָה", hebrew: "מִצְלָלָה" },
    { foreign: "פְּרוֹדוּקְט", hebrew: "מִצְרָךְ" },
    { foreign: "פַּרְוֶה", hebrew: "סְתָמִי" },
    { foreign: "פֶּרְוֶרְטִי", hebrew: "סוֹטֶה" },
    { foreign: "פְּרוֹזֶ'קְטוֹר", hebrew: "זַרְקוֹר" },
    { foreign: "פְּרוֹטֵאִין", hebrew: "חֶלְבּוֹן" },
    { foreign: "פְּרוֹטוֹטִיפּ", hebrew: "אַב טִיפּוּס" },
    { foreign: "פְּרוֹטוֹקוֹל", hebrew: "זִכְרוֹן דְּבָרִים" },
    { foreign: "פְּרוֹיֵקְט", hebrew: "מֵיזָם" },
    { foreign: "פְּרוֹיֶקְטוֹר", hebrew: "מְנַהֵל מֵיזָם" },
    { foreign: "פרוסטטה", hebrew: "עַרְמוֹנִית" },
    { foreign: "פרוססור", hebrew: "מְעַבֵּד" },
    { foreign: "פְּרוֹסְפֵּקְט", hebrew: "עֲלוֹן מֵידָע" },
    { foreign: "פְּרוֹפָּגַנְדָּה", hebrew: "תַּעֲמוּלָה" },
    { foreign: "פְּרוֹפֵּלוֹר", hebrew: "מַדְחֵף" },
    { foreign: "פְּרוֹצֵס", hebrew: "תַּהֲלִיךְ" },
    { foreign: "פרותזה", hebrew: "תּוֹתֶבֶת" },
    { foreign: "פָּרָזִיט", hebrew: "טַפִּיל" },
    { foreign: "פְּרֵזֶנְטוֹר", hebrew: "יַצְּגָן" },
    { foreign: "פַּרְטִיטוּרָה", hebrew: "תַּכְלִיל" },
    { foreign: "פְרִיגִ'ידֵר", hebrew: "מְקָרֵר" },
    { foreign: "פְּרִיזְמָה", hebrew: "מִנְסָרָה" },
    { foreign: "פְרִיזֵר", hebrew: "מַקְפִּיא" },
    { foreign: "פָּרִיטֵטִי", hebrew: "שָׁקוּל" },
    { foreign: "פָּרִיטֵטִיּוּת", hebrew: "שְׁקִילוֹת" },
    { foreign: "פריים טַיְם", hebrew: "שְׁעַת שִׂיא" },
    { foreign: "פְּרַיְמֵרִיז", hebrew: "בְּחִירוֹת מַקְדִּימוֹת" },
    { foreign: "פרימטר", hebrew: "הֶקֵּף" },
    { foreign: "פֵּרִיפֶרְיָאלִי", hebrew: "הֶקֵּפִי" },
    { foreign: "פרלוד", hebrew: "אַקְדָּמָה" },
    { foreign: "פרלין", hebrew: "מֻלְיָה" },
    { foreign: "פְּרֶמְיֵרָה", hebrew: "הַצָּגַת בְּכוֹרָה" },
    { foreign: "פֶּרְסוֹנִיפִיקַצְיָה", hebrew: "הַאֲנָשָׁה" },
    { foreign: "פֶּרְסוֹנָלִי", hebrew: "אִישִׁי" },
    { foreign: "פְּרֶסְטִיזָ'ה", hebrew: "יֻקְרָה" },
    { foreign: "פֶּרְסְפֶּקְטִיבָה", hebrew: "תִּשְׁקֹפֶת" },
    { foreign: "פְרֶסְקוֹ", hebrew: "תַּמְשִׁיחַ" },
    { foreign: "פרעצל", hebrew: "שְׁלוֹבִית" },
    { foreign: "פרפום", hebrew: "בֹּשֶׂם" },
    { foreign: "פרפומריה", hebrew: "תַּמְרוּקִיָּה" },
    { foreign: "פֶּרְפוֹרְמֵנְס", hebrew: "מֵיצָג" },
    { foreign: "פְּרֵפֵקְט", hebrew: "מֻשְׁלָם" },
    { foreign: "פתוגן", hebrew: "מַרְעָן" },
    { foreign: "שֶׁאָטֶל", hebrew: "הֶסֵּעִית" },
    { foreign: "שאסי", hebrew: "שִׁלְדָּה" },
    { foreign: "שוקולטייר", hebrew: "שׁוֹקוֹלָדַאי" },
    { foreign: "שוקר חַשְׁמַלִּי", hebrew: "מַהֲלוֹם" },
    { foreign: "שְׁטַנְץ", hebrew: "דְּפוּס" },
    { foreign: "שְׁטֵקֶר", hebrew: "תֵּקַע" },
    { foreign: "שְׁטְרוּדֶל", hebrew: "כְּרוּכִית" },
    { foreign: "שייבה", hebrew: "דִּסְקִית" },
    { foreign: "שֶׁיְמִינְג", hebrew: "בִּיּוּשׁ" },
    { foreign: "שֵׁיְק", hebrew: "קְצִיף" },
    { foreign: "ראורגניזציה", hebrew: "אִרְגּוּן מֵחָדָשׁ" },
    { foreign: "רָאנֶר", hebrew: "שְׁבִילָה" },
];
